-- 使用 PostgreSQL 管理员账号执行，例如：
-- psql -h 124.174.36.212 -U postgres -d postgres -f deploy/postgres-init.sql
\set ON_ERROR_STOP on

SELECT 'CREATE ROLE lob_browser LOGIN PASSWORD ''1a2d8900d4798c2cbeb3531a27a1096669d2e69e24eb3711'' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION'
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'lob_browser')\gexec

ALTER ROLE lob_browser WITH LOGIN PASSWORD '1a2d8900d4798c2cbeb3531a27a1096669d2e69e24eb3711' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;

SELECT 'CREATE DATABASE lob_browser OWNER lob_browser ENCODING ''UTF8'''
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'lob_browser')\gexec

\connect lob_browser

REVOKE ALL ON DATABASE lob_browser FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE lob_browser TO lob_browser;
GRANT USAGE, CREATE ON SCHEMA public TO lob_browser;
ALTER DEFAULT PRIVILEGES FOR ROLE lob_browser IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lob_browser;
ALTER DEFAULT PRIVILEGES FOR ROLE lob_browser IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO lob_browser;
