const state={tasks:[],current:null,running:false,steps:[]};const $=s=>document.querySelector(s);const list=$("#task-list"),messages=$("#messages"),steps=$("#steps"),prompt=$("#prompt");
function renderTasks(){list.innerHTML=state.tasks.map(t=>`<button class="task-item ${t.id===state.current?.id?'active':''}" data-id="${t.id}">${t.title}<small>${t.status||'未运行'}</small></button>`).join('');list.querySelectorAll('.task-item').forEach(b=>b.onclick=()=>{state.current=state.tasks.find(t=>t.id===b.dataset.id);render()})}
function addMessage(role,text){const el=document.createElement('div');el.className=`message ${role}`;el.innerHTML=`<div class="avatar">${role==='user'?'你':'LOB'}</div><div class="message-body"><div class="message-meta">${role==='user'?'你':'LOB Agent'}</div><p></p></div>`;el.querySelector('p').textContent=text;messages.append(el);messages.scrollTop=messages.scrollHeight}
function render(){if(!state.current)return;$("#task-title").textContent=state.current.title;renderTasks();messages.innerHTML='';state.current.messages.forEach(m=>addMessage(m.role,m.text))}
function renderSteps(){steps.innerHTML=state.steps.map(s=>`<li class="${s.status}"><span class="step-icon"></span><div class="step-text"><strong>${s.label}</strong><small>${s.detail||''}</small></div></li>`).join('');$("#step-badge").textContent=state.steps.length;$("#step-count").textContent=`${state.steps.filter(s=>s.status==='done').length} / 8 steps`}
const wait=ms=>new Promise(r=>setTimeout(r,ms));function setStep(label,detail){state.steps.push({label,detail,status:'running'});renderSteps();return state.steps.length-1}function done(i,detail){state.steps[i].status='done';state.steps[i].detail=detail;renderSteps()}
async function runDemo(){state.running=true;$("#run-status").textContent='正在执行';$("#run-dot").className='status-dot running';$("#approval").hidden=true;$("#result").className='result';$("#result").textContent='Agent 正在执行任务…';state.steps=[];renderSteps();
 let i=setStep('观察当前页面','读取 DOM 与可交互元素');await wait(500);done(i,'找到 4 个可交互元素');$("#progress-bar").style.width='25%';i=setStep('选择下一步动作','模型决定填写表单');await wait(550);done(i,'type(selector, text)');$("#progress-bar").style.width='45%';i=setStep('执行输入动作','填写姓名和邮箱');await wait(600);done(i,'ActionResult: success');$("#progress-bar").style.width='65%';i=setStep('重新观察页面','页面版本已更新');await wait(500);done(i,'observation_id: obs_002');$("#progress-bar").style.width='78%';i=setStep('等待人工审批','提交动作属于高风险操作');state.running=false;$("#run-status").textContent='等待审批';$("#approval").hidden=false;await new Promise(resolve=>{$("#approve").onclick=()=>{$("#approval").hidden=true;resolve()};$("#reject").onclick=()=>{$("#approval").hidden=true;state.steps[i].status='error';$("#run-status").textContent='已拒绝';$("#run-dot").className='status-dot error';$("#result").textContent='任务已停止：审批被拒绝';renderSteps();resolve(false)}});if(state.steps[i].status==='error')return;done(i,'已批准，继续执行');i=setStep('点击提交按钮','click(index=3)');await wait(650);done(i,'提交成功');$("#progress-bar").style.width='100%';$("#run-status").textContent='任务完成';$("#run-dot").className='status-dot done';$("#run-time").textContent='1.8s';$("#result").className='result success';$("#result").textContent='已完成：表单提交成功，页面显示“操作成功”。';$("#page-url").textContent='http://localhost:8000/fixtures/form.html';$("#page-title").textContent='表单测试页';$("#observation-id").textContent='obs_003';$("#page-content").innerHTML='<div class="page-placeholder" style="border-style:solid;color:#287752;background:#f3fcf7">✓ 操作成功</div>';state.current.status='已完成';renderTasks()}
$("#composer").onsubmit=e=>{e.preventDefault();const text=prompt.value.trim();if(!text||state.running)return;state.current={id:crypto.randomUUID(),title:text.slice(0,24),status:'执行中',messages:[{role:'user',text}]};state.tasks.unshift(state.current);prompt.value='';render();addMessage('assistant','我会先观察当前浏览器页面。涉及提交、删除、支付等高风险动作时，我会先请求你的确认。');runDemo()};$("#new-task").onclick=()=>{messages.innerHTML='';$("#task-title").textContent='新建浏览器任务';prompt.focus()};$("#clear-tasks").onclick=()=>{state.tasks=[];state.current=null;renderTasks();messages.innerHTML=''};document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>{prompt.value=b.dataset.text;prompt.focus()});document.querySelectorAll('.panel-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$("#run-view").hidden=b.dataset.panel!=='run';$("#page-view").hidden=b.dataset.panel!=='page'});$("#settings").onclick=()=>alert('设置面板将在后端 API 接入后开放。');renderTasks();
document.querySelector("#composer").classList.add("composer");
$("#new-task").onclick=()=>{state.current=null;state.running=false;state.steps=[];messages.innerHTML='';prompt.value='';$("#task-title").textContent='新建浏览器任务';$("#run-status").textContent='等待任务';$("#run-dot").className='status-dot idle';$("#progress-bar").style.width='0';$("#step-count").textContent='0 / 8 steps';$("#step-badge").textContent='0';$("#run-time").textContent='—';$("#approval").hidden=true;$("#result").className='result empty';$("#result").textContent='任务结果将在这里显示';$("#page-url").textContent='about:blank';$("#page-title").textContent='等待页面';$("#observation-id").textContent='—';$("#page-content").innerHTML='<div class="page-placeholder">尚未开始观察页面</div>';renderSteps();renderTasks();prompt.focus()};
$("#composer").onsubmit=async e=>{e.preventDefault();const text=prompt.value.trim();if(!text||state.running)return;const button=e.submitter;button.disabled=true;try{const response=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:text})});if(!response.ok)throw new Error('任务服务不可用');const saved=await response.json();state.current={id:saved.id,title:text.slice(0,24),status:'执行中',messages:[{role:'user',text}]};state.tasks.unshift(state.current);prompt.value='';render();addMessage('assistant','任务已保存到 PostgreSQL。我会先观察当前浏览器页面。涉及提交、删除、支付等高风险动作时，我会先请求你的确认。');runDemo()}catch(error){addMessage('system',`任务创建失败：${error.message}`)}finally{button.disabled=false}};
